name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Set this in your GitHub secrets
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # Set this in your GitHub secrets
          project-name: your-project-name  # Replace with your Cloudflare Pages project name
          directory: build/client  # The output directory of your build
